/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "record_redis_constants.h"



const record_redisConstants g_record_redis_constants;

record_redisConstants::record_redisConstants() {
}



