// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "recordService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class recordServiceHandler : virtual public recordServiceIf {
 public:
  recordServiceHandler() {
    // Your initialization goes here
  }

  void Update(std::string& _return, const reqinfo& request) {
    // Your implementation goes here
    printf("Update\n");
  }

  void GetAllKeyValue(resinfo& _return, const std::string& type) {
    // Your implementation goes here
    printf("GetAllKeyValue\n");
  }

  void CheckOneRecord(std::string& _return, const reqinfo& request) {
    // Your implementation goes here
    printf("CheckOneRecord\n");
  }

  void DelOneRecord(std::string& _return, const reqinfo& request) {
    // Your implementation goes here
    printf("DelOneRecord\n");
  }

  void PushRunnableType(std::string& _return, const std::string& type) {
    // Your implementation goes here
    printf("PushRunnableType\n");
  }

  void DelRunnableType(std::string& _return, const std::string& type) {
    // Your implementation goes here
    printf("DelRunnableType\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<recordServiceHandler> handler(new recordServiceHandler());
  shared_ptr<TProcessor> processor(new recordServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

