/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef record_redis_CONSTANTS_H
#define record_redis_CONSTANTS_H

#include "record_redis_types.h"



class record_redisConstants {
 public:
  record_redisConstants();

};

extern const record_redisConstants g_record_redis_constants;



#endif
